version: "3.9"
services:
  weather:
    container_name: myWeather
    build:
      context: ./
      dockerfile: ./myWeather/Dockerfile
    ports:
      - "8095:8095"
    networks:
      - spring
    restart: always

networks:
  spring:
    name: spring